apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: "2025-06-05T14:36:36Z"
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: dpf-provisioning-controller-manager
    applyset.kubernetes.io/part-of: applyset-Adq8goFoWaQPC0zfgewt_Rel4dQcv2VCXrCRMgjWOuo-v1
    dpu.nvidia.com/component: dpf-provisioning-controller-manager
  name: dpf-provisioning-dms-role
  resourceVersion: "9109388"
  uid: 06f7db03-c3e6-4368-b8f0-30abf1de379a
rules:
- apiGroups:
  - provisioning.dpu.nvidia.com
  resources:
  - dpunodes
  verbs:
  - create
  - get
- apiGroups:
  - provisioning.dpu.nvidia.com
  resources:
  - dpudevices
  verbs:
  - create
  - get
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  verbs:
  - create
  - get
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
