# MCE Instance with HyperShift enabled
# Apply this AFTER the CSV shows Succeeded status
---
apiVersion: multicluster.openshift.io/v1
kind: MultiClusterEngine
metadata:
  name: multiclusterengine
  namespace: multicluster-engine
spec:
  availabilityConfig: Basic
  targetNamespace: multicluster-engine
  overrides:
    components:
    - name: hypershift
      enabled: true
    - name: hypershift-local-hosting
      enabled: true
---
# Optional: ManagedClusterAddOn for HyperShift (if needed)
apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ManagedClusterAddOn
metadata:
  name: hypershift-addon
  namespace: local-cluster
spec:
  installNamespace: open-cluster-management-agent-addon