site_name: NVIDIA DPF on OpenShift

# Use Material for MkDocs theme
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - content.code.annotate
    - content.tabs.link
    - content.action.edit
  palette:
    - scheme: default
      primary: blue
      accent: light blue

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

plugins:
  - search
  - mermaid2

# Simplified flat navigation
nav:
  - Home: index.md
  - Getting Started:
    - Introduction: introduction.md
    - Prerequisites: prerequisites.md
  - Installation:
    - Complete Deployment: full-installation.md
    - OpenShift Cluster Creation: cluster-creation.md
    - DPF Operator Installation: dpf-operator.md
    - DPU Provisioning: dpu-provisioning.md
    - DOCA Services Deployment: doca-services.md
  - Operations:
    - Troubleshooting: troubleshooting.md
  - Reference:
    - Automation Reference: automation-reference.md
    - FAQ: faq.md
    - Resources: resources.md

# Add custom JavaScript to fix navigation
extra_javascript:
  - assets/javascripts/nav-fix.js

docs_dir: docs

# Important: for Netlify, enable directory URLs
use_directory_urls: true
