---
apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: argocd
  namespace: dpf-operator-system
spec:
  nodePlacement:
    nodeSelector:
      node-role.kubernetes.io/control-plane: ""
    tolerations:
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule

  server:
    route:
      enabled: true
    labels:
      ovn.dpu.nvidia.com/skip-injection: ""

  controller:
    labels:
      ovn.dpu.nvidia.com/skip-injection: ""

  repo:
    labels:
      ovn.dpu.nvidia.com/skip-injection: ""

  redis:
    labels:
      ovn.dpu.nvidia.com/skip-injection: ""

  applicationSet:
    enabled: false

  sso:
    dex:
      openShiftOAuth: false

  notifications:
    enabled: false