# Security Context Constraints for ArgoCD deployment on OpenShift
# This file grants existing OpenShift SCCs to ArgoCD service accounts

---
# Grant anyuid SCC to ArgoCD Redis service account
# This allows Redis to run as user 999
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-redis-anyuid-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
- kind: ServiceAccount
  name: default
  namespace: dpf-operator-system
- kind: ServiceAccount
  name: argo-cd-argocd-redis
  namespace: dpf-operator-system

---
# Grant privileged SCC to ArgoCD service accounts that need it
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-privileged-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
- kind: ServiceAccount
  name: default
  namespace: dpf-operator-system
- kind: ServiceAccount
  name: argo-cd-argocd-application-controller
  namespace: dpf-operator-system
- kind: ServiceAccount
  name: argo-cd-argocd-repo-server
  namespace: dpf-operator-system
- kind: ServiceAccount
  name: argo-cd-argocd-server
  namespace: dpf-operator-system