apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 99-worker-nm-dispatcher-auto-bridge
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
        - contents:
            source: data:text/plain;charset=utf-8;base64,IyEvYmluL2Jhc2gKCklOVEVSRkFDRT0iJDEiCkFDVElPTj0iJDIiCgojIFdoZW4gYW55IGludGVyZmFjZSBlbmRpbmcgd2l0aCBmMHYwIGNvbWVzIHVwLCBhZGQgaXQgdG8gYnItZHB1CmlmIFtbICIkSU5URVJGQUNFIiA9PSAqZjB2MCBdXSAmJiBbICIkQUNUSU9OIiA9ICJ1cCIgXTsgdGhlbgogICAgIyBDaGVjayBpZiBici1kcHUgZXhpc3RzCiAgICBpZiBpcCBsaW5rIHNob3cgYnItZHB1ICY+L2Rldi9udWxsOyB0aGVuCiAgICAgICAgIyBBZGQgdG8gYnJpZGdlIGlmIG5vdCBhbHJlYWR5IHRoZXJlCiAgICAgICAgaWYgISBicmlkZ2UgbGluayBzaG93IHwgZ3JlcCAtcSAiJElOVEVSRkFDRS4qbWFzdGVyIGJyLWRwdSI7IHRoZW4KICAgICAgICAgICAgbm1jbGkgY29ubmVjdGlvbiBhZGQgdHlwZSBicmlkZ2Utc2xhdmUgXAogICAgICAgICAgICAgICAgY29uLW5hbWUgImJyaWRnZS1zbGF2ZS0kSU5URVJGQUNFIiBcCiAgICAgICAgICAgICAgICBpZm5hbWUgIiRJTlRFUkZBQ0UiIFwKICAgICAgICAgICAgICAgIG1hc3RlciBici1kcHUgXAogICAgICAgICAgICAgICAgY29ubmVjdGlvbi5hdXRvY29ubmVjdCB5ZXMgXAogICAgICAgICAgICAgICAgY29ubmVjdGlvbi5hdXRvY29ubmVjdC1yZXRyaWVzIC0xCiAgICAgICAgZmkKICAgIGZpCmZp
          mode: 0755
          overwrite: true
          path: /etc/NetworkManager/dispatcher.d/99-auto-bridge-port