# ArgoCD Values for DPF v25.7 Deployment
# This file contains the Helm values for ArgoCD deployment
# ArgoCD is installed as a prerequisite before DPF operator

## Disable the ApplicationSet controller
applicationSet:
  replicas: 0

## Disable Dex (OIDC authentication)
dex:
  enabled: false

## Disable notifications controller
notifications:
  enabled: false

## Redis configuration for OpenShift compatibility
redis:
  # Override security context to work with OpenShift SCCs
  securityContext:
    runAsNonRoot: true
    runAsUser: null  # Let OpenShift assign the user
    fsGroup: null    # Let OpenShift assign the fsGroup
  containerSecurityContext:
    runAsNonRoot: true
    runAsUser: null
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL

## Global configuration
global:
  # Pod labels to prevent OVN injection
  podLabels:
    ovn.dpu.nvidia.com/skip-injection: ""
  
  # Node affinity to ensure ArgoCD runs on control plane nodes
  affinity:
    nodeAffinity:
      # Enforce hard node affinity
      type: hard
      # Match control plane nodes
      matchExpressions:
        - key: "node-role.kubernetes.io/control-plane"
          operator: Exists
  
  # Tolerations for control plane taints
  tolerations:
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule