apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-nfd-operator
  namespace: openshift-nfd
spec:
  channel: 'stable'
  installPlanApproval: Automatic
  name: openshift-nfd-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-nfd
  labels:
    openshift.io/cluster-monitoring: "true"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: nfd-operator-group
  namespace: openshift-nfd
spec:
  targetNamespaces:
  - openshift-nfd
