nameOverride: ovn-kubernetes

# Enable control plane for OVN
controlPlaneManifests:
  enabled: true
  cniBinDir: "/var/lib/cni/bin/"
  cniConfDir: "/run/multus/cni/net.d"

# Enable node with DPU manifests
nodeWithDPUManifests:
  enabled: true
  nodeMgmtPortNetdev: <DPU_P0_VF1>
  dpuServiceAccountNamespace: dpf-operator-system
  cniBinDir: "/var/lib/cni/bin/"
  cniConfDir: "/run/multus/cni/net.d"

# Enable common manifests
commonManifests:
  enabled: true

# Enable regular node manifests for nodes without DPU
nodeWithoutDPUManifests:
  enabled: true
  cniBinDir: "/var/lib/cni/bin/"
  cniConfDir: "/run/multus/cni/net.d"

global:
  imagePullSecretName: "dpf-pull-secret"

k8sAPIServer: https://<TARGETCLUSTER_API_SERVER_HOST>:<TARGETCLUSTER_API_SERVER_PORT>
podNetwork: <POD_CIDR>/24
serviceNetwork: <SERVICE_CIDR>
gatewayOpts: --gateway-interface=<DPU_P0>

# DPU manifests configuration (for DPUService deployment)
dpuManifests:
  enabled: false  # Will be enabled by DPUService
  cniBinDir: "/var/lib/cni/bin/"
  cniConfDir: "/run/multus/cni/net.d"

ovn-kubernetes-resource-injector:
  enabled: true
  resourceName: openshift.io/bf3-p0-vfs
  nadName: dpf-ovn-kubernetes