---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sriov-test-master
  labels:
    app: sriov-test-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sriov-test-master
  template:
    metadata:
      labels:
        app: sriov-test-master
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: sriov-test-master
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      containers:
      - name: nginx
        securityContext:
          privileged: true
          capabilities:
            add:
            - NET_ADMIN
        image: nicolaka/netshoot
        command: ["nc", "-kl", "5000"]
        ports:
        - containerPort: 5000
          name: tcp-server
        resources:
          requests:
            cpu: 1
            memory: 1Gi
          limits:
            cpu: 1
            memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: sriov-test-master
  labels:
    app: sriov-test-master
spec:
  selector:
    app: sriov-test-master
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: sriov-test-master-nodeport
  labels:
    app: sriov-test-master
spec:
  type: NodePort
  selector:
    app: sriov-test-master
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sriov-test-worker
  labels:
    app: sriov-test-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sriov-test-worker
  template:
    metadata:
      labels:
        app: sriov-test-worker
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: sriov-test-worker
      nodeSelector:
        feature.node.kubernetes.io/dpu-enabled: "true"
      containers:
      - name: nginx
        securityContext:
          privileged: true
          capabilities:
            add:
            - NET_ADMIN
        image: nicolaka/netshoot
        command: ["nc", "-kl", "5000"]
        ports:
        - containerPort: 5000
          name: tcp-server
        resources:
          requests:
            cpu: 16
            memory: 6Gi
          limits:
            cpu: 16
            memory: 6Gi
---
apiVersion: v1
kind: Service
metadata:
  name: sriov-test-worker
  labels:
    app: sriov-test-worker
spec:
  selector:
    app: sriov-test-worker
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: sriov-test-worker-nodeport
  labels:
    app: sriov-test-worker
spec:
  type: NodePort
  selector:
    app: sriov-test-worker
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sriov-test-worker-hostnetwork
  labels:
    app: sriov-test-worker-hostnetwork
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sriov-test-worker-hostnetwork
  template:
    metadata:
      labels:
        app: sriov-test-worker-hostnetwork
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: sriov-test-worker-hostnetwork
      nodeSelector:
        feature.node.kubernetes.io/dpu-enabled: "true"
      hostNetwork: true
      containers:
      - name: nginx
        securityContext:
          privileged: true
          capabilities:
            add:
            - NET_ADMIN
        image: nicolaka/netshoot
        command: ["nc", "-kl", "5000"]
        ports:
        - containerPort: 5000
          name: tcp-server
        resources:
          requests:
            cpu: 1
            memory: 1Gi
          limits:
            cpu: 1
            memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: sriov-test-worker-hostnetwork
  labels:
    app: sriov-test-worker-hostnetwork
spec:
  selector:
    app: sriov-test-worker-hostnetwork
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: sriov-test-worker-hostnetwork-nodeport
  labels:
    app: sriov-test-worker-hostnetwork
spec:
  type: NodePort
  selector:
    app: sriov-test-worker-hostnetwork
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
