apiVersion: svc.dpu.nvidia.com/v1alpha1
kind: DPUServiceConfiguration
metadata:
  name: doca-blueman-service
  namespace: dpf-operator-system
spec:
  deploymentServiceName: "doca-blueman-service"
  serviceConfiguration:
    helmChart:
      values:
        imagePullSecrets:
        - name: dpf-pull-secret