apiVersion: svc.dpu.nvidia.com/v1alpha1
kind: DPUServiceTemplate
metadata:
  name: doca-blueman-service
  namespace: dpf-operator-system
spec:
  deploymentServiceName: "doca-blueman-service"
  resourceRequirements:
    cpu: 1
    memory: 1Gi
    storage: 1Gi
  helmChart:
    source:
      repoURL: https://helm.ngc.nvidia.com/nvidia/doca
      chart: doca-blueman
      version: "1.0.5"