apiVersion: svc.dpu.nvidia.com/v1alpha1
kind: DPUServiceTemplate
metadata:
  name: doca-telemetry-service
  namespace: dpf-operator-system
spec:
  deploymentServiceName: "doca-telemetry-service"
  resourceRequirements:
    cpu: 1
    memory: 1Gi
    storage: 1Gi
  helmChart:
    source:
      repoURL: <DTS_HELM_REPO_URL>
      chart: doca-telemetry
      version: <DTS_HELM_CHART_VERSION>
    values:
      hostVolumePrefix: "/var/lib"
