apiVersion: svc.dpu.nvidia.com/v1alpha1
kind: DPUService
metadata:
  name: flannel
  namespace: dpf-operator-system
spec:
  helmChart:
    source:
      chart: dpu-networking
      path: ""
      repoURL: oci://ghcr.io/nvidia
      version: DPF_VERSION
    values:
      flannel:
        enabled: true
        flannel:
          cniBinDir: /var/lib/cni/bin/
          cniConfDir: /run/multus/cni/net.d/
          mtu: "1500"
          skipCNIConfigInstallation: false
        imagePullSecrets:
          - name: dpf-pull-secret
