---
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: bf3-p0-vfs
  namespace: openshift-sriov-network-operator
spec:
  nicSelector:
    deviceID: "a2dc"
    vendor: "15b3"
    pfNames:
    - <DPU_INTERFACE>#2-<NUM_VFS-1>
  nodeSelector:
    node-role.kubernetes.io/worker: ""
  numVfs: <NUM_VFS>
  resourceName: bf3-p0-vfs
  resourcePrefix: openshift.io
  isRdma: true
  externallyManaged: true
  deviceType: netdevice
  linkType: eth
